services:
  web:
    build: .
    container_name: orchestration
    command: ["python", "manage.py", "runserver", "0.0.0.0:8080"]
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    volumes:
      - ./orchestration/static:/OrchestrationRouteurCISCO/orchestration/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - MYSQL_HOST=mysql_db
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=orchestration_routeur

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: orchestration_routeur
    ports:
      - "3306:3306"
