[tool.black]
line-length = 88
target-version = ['py312']  # adapte selon ta version

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["orchestration", "OrchestrationRouteurCISCO"]
skip = ["migrations"]  # ignore les migrations Django
