POST http://localhost:8000/orchestration/interface/
Content-Type: application/json

{
    "interfaceName": "eth0",
    "ipAddress": "192.168.1.1",
    "subnetMask": "255.255.255.0",
    "subInterface": "eth0.1",
    "action": "enable",
    "mode": "static"
}
