#POST http://127.0.0.1:8000/orchestration/api/routers/
#Content-Type: application/json

POST http://127.0.0.1:8000/api/routers/
Content-Type: application/json

{
    "name": "Routeur1",
    "ip_address": "192.168.1.1",
    "status": "Active"
}

