# Generated by Django 4.2.19 on 2025-02-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('orchestration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='interface_name',
        ),
        migrations.RemoveField(
            model_name='router',
            name='sub_interface',
        ),
        migrations.RemoveField(
            model_name='router',
            name='subnet_mask',
        ),
        migrations.RemoveField(
            model_name='router',
            name='user',
        ),
        migrations.AddField(
            model_name='router',
            name='device_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='router',
            name='hostname',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestration.router')),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('subnet_mask', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=100)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestration.router')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(max_length=100)),
                ('interface_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestration.interface')),
                ('router_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestration.router')),
            ],
        ),
    ]
