# Generated by Django 5.1.6 on 2025-02-22 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0002_remove_router_interface_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Configuration",
        ),
    ]
