# Generated by Django 5.1.1 on 2025-07-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orchestration",
            "0004_alter_interface_status_alter_interface_subnet_mask_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="router",
            name="enable_password",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="router",
            name="password",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="router",
            name="username",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("normal", "Normal")],
                default="normal",
                max_length=100,
            ),
        ),
    ]
